default: &default
  adapter: postgresql
  encoding: unicode
  # For Rails 6.1 and above, use `db/sockets` for socket connections
  # socket: <%= Rails.root.join("db/sockets/pg.sock") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 
  host: localhost

development:
  <<: *default
  database: tree_app_development
